# Generated by Django 4.2.6 on 2023-10-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaImpuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_categoria_impuesto", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "CategoriasImpuestos",
            },
        ),
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_categoria_producto", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "CategoriasProductos",
            },
        ),
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_metodo_pago", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "MetodosPagos",
            },
        ),
        migrations.CreateModel(
            name="Organizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_organizacion", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Organizaciones",
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "cod_proveedor",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("nombre_empresa", models.CharField(max_length=50)),
                ("rut_proveedor", models.CharField(max_length=12)),
            ],
            options={
                "verbose_name_plural": "Proveedores",
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_servicio", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Servicios",
            },
        ),
        migrations.CreateModel(
            name="ServicioImpresionOrganizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_servicio_impresion_organizacion",
                    models.CharField(max_length=50),
                ),
                ("valor_metro_lineal", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "ServiciosImpresionOrganizaciones",
            },
        ),
        migrations.CreateModel(
            name="TipoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_tipo_usuario", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "TiposUsuarios",
            },
        ),
        migrations.CreateModel(
            name="VentaOrganizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medidas_ventas_organizacion", models.CharField(max_length=50)),
                ("proyecto_ventas_organizacion", models.CharField(max_length=50)),
                ("solicitante_ventas_organizacion", models.CharField(max_length=50)),
                (
                    "fk_organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.organizacion",
                    ),
                ),
                (
                    "fk_servicio_impresion_organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.servicioimpresionorganizacion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "VentasOrganizacion",
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_venta", models.DateField()),
                (
                    "fk_metodo_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.metodopago",
                    ),
                ),
                (
                    "fk_servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.servicio",
                    ),
                ),
                (
                    "fk_ventas_organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.ventaorganizacion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ventas",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=50)),
                ("contrasena_usuario", models.CharField(max_length=50)),
                (
                    "fk_tipo_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.tipousuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referencia", models.CharField(max_length=40)),
                ("nombre_producto", models.CharField(max_length=40)),
                ("cod_barra_producto", models.CharField(max_length=20)),
                ("stock", models.IntegerField()),
                ("precio_venta_mas_impuesto", models.IntegerField()),
                ("precio_neto", models.IntegerField()),
                ("estado_en_stock", models.BooleanField()),
                (
                    "fk_categoria_impuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.categoriaimpuesto",
                    ),
                ),
                (
                    "fk_categoria_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.categoriaproducto",
                    ),
                ),
                (
                    "fk_proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.CreateModel(
            name="ItemVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_vendida", models.IntegerField()),
                ("precio_unitario", models.IntegerField()),
                ("importe", models.IntegerField()),
                (
                    "cod_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.producto",
                    ),
                ),
                (
                    "cod_venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.venta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ItemsVentas",
            },
        ),
    ]
