# Generated by Django 4.2.6 on 2023-10-22 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metodopago",
            options={"verbose_name_plural": "MetodosPago"},
        ),
        migrations.RemoveField(
            model_name="producto",
            name="fk_proveedor",
        ),
        migrations.DeleteModel(
            name="Proveedor",
        ),
    ]
