# Generated by Django 4.2.6 on 2023-10-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_metodopago_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_empresa", models.CharField(max_length=50)),
                ("rut_proveedor", models.CharField(max_length=12)),
            ],
            options={
                "verbose_name_plural": "Proveedores",
            },
        ),
        migrations.AddField(
            model_name="producto",
            name="fk_proveedor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="website.proveedor",
            ),
            preserve_default=False,
        ),
    ]
