# Generated by Django 4.2.6 on 2023-10-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_venta_importe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="fk_ventas_organizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="website.ventaorganizacion",
            ),
        ),
    ]
