# Generated by Django 4.2.6 on 2023-11-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_venta_fk_ventas_organizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaimpuesto",
            name="nombre_categoria_impuesto",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="categoriaproducto",
            name="nombre_categoria_producto",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="metodopago",
            name="nombre_metodo_pago",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="organizacion",
            name="nombre_organizacion",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="cod_barra_producto",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre_producto",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="referencia",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre_empresa",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="rut_proveedor",
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="nombre_servicio",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="servicioimpresionorganizacion",
            name="nombre_servicio_impresion_organizacion",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="tipousuario",
            name="nombre_tipo_usuario",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nombre_usuario",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fecha_venta",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
