# Generated by Django 4.2.6 on 2023-11-14 01:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_alter_categoriaimpuesto_nombre_categoria_impuesto_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemventa",
            old_name="cod_producto",
            new_name="fk_cod_producto",
        ),
        migrations.RenameField(
            model_name="itemventa",
            old_name="cod_venta",
            new_name="fk_cod_venta",
        ),
    ]
