# Generated by Django 4.2.6 on 2023-11-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_rename_cod_producto_itemventa_fk_cod_producto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ventaorganizacion",
            name="medidas_ventas_organizacion",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
