# Generated by Django 4.2.6 on 2023-11-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_alter_ventaorganizacion_medidas_ventas_organizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="cod_barra_producto",
            field=models.CharField(max_length=85, unique=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="referencia",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
