# Generated by Django 4.2.6 on 2023-11-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_alter_producto_cod_barra_producto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="importe",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
