# Generated by Django 4.2.6 on 2023-11-22 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_alter_venta_importe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaimpuesto",
            name="nombre_categoria_impuesto",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_letras",
                        message="Este campo solo acepta letras y espacios.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="categoriaproducto",
            name="nombre_categoria_producto",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_letras",
                        message="Este campo solo acepta letras y espacios.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="metodopago",
            name="nombre_metodo_pago",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_letras",
                        message="Este campo solo acepta letras y espacios.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="organizacion",
            name="nombre_organizacion",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_letras",
                        message="Este campo solo acepta letras y espacios.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre_producto",
            field=models.CharField(
                max_length=40,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_letras",
                        message="Este campo solo acepta letras y espacios.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre_empresa",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_letras",
                        message="Este campo solo acepta letras y espacios.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="rut_proveedor",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_rut",
                        message="Formato de RUT no válido. Utilice un formato como 12345678-9.",
                        regex="^\\d{1,8}-[1-9kK]$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="nombre_servicio",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_letras",
                        message="Este campo solo acepta letras y espacios.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tipousuario",
            name="nombre_tipo_usuario",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_letras",
                        message="Este campo solo acepta letras y espacios.",
                        regex="^[A-Za-z ]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="importe",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
