# Generated by Django 4.2.6 on 2023-12-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_alter_itemventa_fk_cod_producto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventaorganizacion",
            name="cantidad_vendida",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
