# Generated by Django 4.2.6 on 2024-06-19 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_ventaorganizacion_cantidad_vendida"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="fk_ventas_organizacion",
        ),
        migrations.RemoveField(
            model_name="ventaorganizacion",
            name="cantidad_vendida",
        ),
        migrations.RemoveField(
            model_name="ventaorganizacion",
            name="fk_servicio_impresion_organizacion",
        ),
        migrations.RemoveField(
            model_name="ventaorganizacion",
            name="medidas_ventas_organizacion",
        ),
        migrations.AddField(
            model_name="venta",
            name="fk_usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="website.usuario",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ventaorganizacion",
            name="importe_total",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemventa",
            name="fk_cod_producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="website.producto"
            ),
        ),
        migrations.AlterField(
            model_name="itemventa",
            name="fk_cod_venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="website.venta"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fk_categoria_impuesto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="website.categoriaimpuesto",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fk_categoria_producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="website.categoriaproducto",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fk_proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="website.proveedor"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="fk_tipo_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="website.tipousuario"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fk_metodo_pago",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="website.metodopago"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fk_servicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="website.servicio"
            ),
        ),
        migrations.AlterField(
            model_name="ventaorganizacion",
            name="fk_organizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="website.organizacion",
            ),
        ),
        migrations.CreateModel(
            name="ItemVentaOrganizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medidas_ventas_organizacion",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                ("cantidad_vendida", models.IntegerField()),
                ("importe_item_venta_organizacion", models.IntegerField()),
                (
                    "fk_servicio_impresion_organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.servicioimpresionorganizacion",
                    ),
                ),
                (
                    "fk_venta_organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="website.ventaorganizacion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "VentasOrganizacion",
            },
        ),
    ]
