# Generated by Django 4.2.6 on 2024-06-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_remove_venta_fk_ventas_organizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventaorganizacion",
            name="fk_cod_venta",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="website.venta",
            ),
            preserve_default=False,
        ),
    ]
