# Generated by Django 4.2.6 on 2024-07-04 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_ventaorganizacion_fk_cod_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena_usuario',
            field=models.CharField(default='pbkdf2_sha256$600000$MIYW3BHEb0x5vUDvFdvrHN$YUJNV+ezRPcJjbyh/nQgkdYY/DRkPFnqOG8sbGppNr0=', max_length=128),
        ),
    ]
