# Generated by Django 4.2.6 on 2024-07-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_usuario_is_active_usuario_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena_usuario',
            field=models.CharField(max_length=128),
        ),
    ]
