# Generated by Django 4.2.6 on 2024-07-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_usuario_contrasena_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='website_usuarios',
        ),
    ]
